version: "3.7"

services:
  webserver:
    build:
      context: .
    container_name: 'coar_notify_php'
    ports:
      - "8060:80"
    networks:
      - coar_notify_network
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    env_file:
      - docker/mysql.env
  database:
    image: "mysql:5.7"
    container_name: 'coar_notify_database'
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql
    env_file:
      - docker/mysql.env
    networks:
      - coar_notify_network
networks:
  coar_notify_network: