version: "3.7"

services:
  webserver:
    build:
      context: .
    container_name: 'coar_notify_php'
    ports:
      - "8060:8080"
    networks:
      - coar_notify_network
    depends_on:
      - database
    env_file:
      - docker/mariadb.env
  database:
    image: "mariadb:latest"
    container_name: 'coar_notify_mariadb'
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql
    env_file:
      - docker/mariadb.env
    networks:
      - coar_notify_network
networks:
  coar_notify_network: